### PR TITLE
Fixed duplicate address issue

### LINKED ISSUE #1809: Customer Address getting duplicated if account was created on shipping step and order was completed
**Description**:
Customer Address getting duplicated if account was created on shipping step and order was completed 

**Expected behavior**:
Address without duplicates is added in Address book

**To Reproduce**:
1. Add product to cart
2. Create account on shipping step
3. Complete order
4. Open address book in my account

**Actual result**:
Address getting duplicated
image

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #1809
Removed new customer address saving from the shipping step since addresses are saved on billing step.

### CODE REVIEW

**Comment by alfredsgenkins** [comment]
I think this is not correct. You should not save billing address if it was marked "same as shipping", if not, two addresses must appear.

**Review by alfredsgenkins — CHANGES_REQUESTED** [review]
I think this is not correct. You should not save billing address if it was marked "same as shipping", if not, two addresses must appear.

**Comment by zans-laksa** [comment]
Then the bug is more serious, since the address that is saved on the billing state is set as default for both billing and shipping, while the address that was saved on the shipping step is not default for the shipping.
Probably need to repair address saving on both steps.

**Comment by zans-laksa** [comment]
Closing this since there is another solution.
See #2094

**Pull request closed without merging**
