### PR TITLE
3658/datetime format support

### PR DESCRIPTION
**Pull request by tatiana-scandi**
**Related issue(s) 1:**
* Fixes https://github.com/scandipwa/scandipwa/issues/3717

**Problem 1:**
* We are trying to convert string like `2000-01-01 <time>` to date. FF and Safari fail to convert such format (under fail to convert I mean execution of `new Date('2000-01-01 <time>'))`. As a result `NaN-NaN-NaN NaN:NaN` is passed in request to the server.

**Solution 1:**
* Use format with slashes instead of dashes. Chrome, FF and Safari convert date correctly.
**Related issue(s) 1:**
* Fixes https://github.com/scandipwa/scandipwa/issues/3717

**Related issue(s) 2:**
* Fixes https://github.com/scandipwa/scandipwa/issues/3659, issue 1

**Problem 2:**
* Input width is restricted to 250px, while actual length of date entered may be longer (it depends on user OS settings, we can't predict how long exactly).

**Solution 2:**
* Replace width with `min-width`, so that if date doesn't fit in, the input is extended.

**Related issue(s) 3:**
* Fixes https://github.com/scandipwa/scandipwa/issues/3659, issue 2

**Problem 3:**
* Product is added to wishlist correctly, but when adding from wishlist to cart, entered options are not passed in request to the server.

**Solution 3:**
* Add date/datetime/time options to `addProductsToCart request` body.

**Related issue(s) 4:**
* Fixes https://github.com/scandipwa/scandipwa/issues/3720

**Problem 4:**
* No support for this Magento feature.

**Solution 4:**
* Parse `year_range` from response, set `min` and `max` options to date/datetime input, that restricts year range allowed.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1.1 Safari - fixed 
1.2 FF: Can reproduce 
Maybe it causes because I entered data and time manually. Date picker doesn't appear when clicking on data&time field
Screenshot 2021-11-09 at 12 29 16
2. Fixed
3. Fixed
4. 'If blank, the field defaults to the current year.' is written in [Magento guide ](https://docs.magento.com/user-guide/stores/attribute-date-time-options.html)
Please, add the same logic in our theme
5. FF crash when tapping Date and Time field or Date field  (It works on master) https://drive.google.com/file/d/1Ogp5baMApvmCiRNuxrs9PF248JMEwkcQ/view?usp=sharing

**Comment by tatiana-scandi** [comment]
1.2 - need more details on how to reproduce (on pause for now). FF v94 on MacOS - works fine, date-picker appears, product added to cart
4 - fixed
5 - tried on iOS FF and Android FF - works fine for me. Can I reproduce the issue on any BrowserStack device?

**Comment by aleksandrakorolova** [comment]
1.2 FF v 92

4.Can't change year if field **to** stays blank in Admin panel. It's 2021 on FE
**Expected result:**
 'If blank, the field defaults **to** the current year.' (for example, **from** is set to 2000 and **to** is empty => User can select year from 2000 to 2021)
 
5.Today can't reproduce on my device

**Comment by tatiana-scandi** [comment]
Replaced by https://github.com/scandipwa/scandipwa/pull/3834

**Pull request closed without merging**
