### PR TITLE
#3232 Modified the vertical alignment of table cells on CMS Pages

### PR DESCRIPTION
**Pull request by Mohamed-Ahmed711**
**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/3232

**Problem:**
* When adding an image to table cells on CMS page the vertical alignment of the neighboring cells gets broken
* When adding an image with specified width and height the image crosses to the neighboring cells in the table 

**In this PR:**
* Added td selector with vertical-align property in CmsPage.Style in route 
* Added Added img selector inside the td selector with properties of height, max-height, min-height, and max-width

### CODE REVIEW

**Comment by Elena-Evsa** [comment]
1. Can you, please, save proportion for lengh and hight of specific image on screenshot 
image
image

2.  Text in cell should have top alligment by defualt, not middle
image

**Comment by Elena-Evsa** [comment]
1. Still can reproduce for image шт this cell without set dimensions 
image

**Comment by Mohamed-Ahmed711** [comment]
Can you please clarify more, currently the image height and width is proportional to the height and width of the table cell, and if the user specifies height and width more than the table cell, the image will have the maximum height and width of the table cell only and it won't cross the cell borders.

**Comment by Elena-Evsa** [comment]
1. Save proportion for lengh and hight of specific **image** on screenshot. Don't use proportions of the table cell.
As expected result open link: http://scandipwapmrev.indvp.com/demo/about-us and have a look on behavior of Luma

**Comment by Elena-Evsa** [comment]
Still wrong proportions in images
image
image

**Comment by Elena-Evsa** [comment]
1. Proportions saved
2. Falied: proportions is saved, but maximum dimention is not according to cell and empty space in row present 
image

**Comment by aleksandrakorolova** [comment]
Closed because this issue is fixed in #4194

**Pull request closed without merging**
