### PR TITLE
#4454 - fixed button covering another button on small height devices

### PR DESCRIPTION
**Pull request by florianf22**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4454

**Problem:**
* On very small devices, like iphone 7 or older, two buttons were covering each other on the Thank You page. The 'continue Shopping button' was position fixed and it's okay when the device height is big enough. However, on very small devices, that positioning didn't really work.

**In this PR:**
*  So, what I did was to, instead of fixed, make the button position absolute. Now, by default, all the wrappers between the button and the main (the element I wanted the button to be relative to) had position relative by default. Made sure that all the wrappers has a position relative. that way, you get the default fixed position behaviour, but also no covering when device height is too small.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Button 'Continue shopping' is hidden under Navigation bar when opening thank you page. Please, return previous logic and fix it
Expected result: page scrolls under Continue shopping but not overlaps it as it works in checkout
Screenshot 2022-03-16 at 10 05 13

**Comment by florianf22** [comment]
250DE56D-D1B6-423D-84A4-28894C6288DA

**Comment by aleksandrakorolova** [comment]
There is a gap between 'Continue Shopping' button and Navigation bar and user can see page content through this gap 
https://drive.google.com/file/d/1pCgw4SEq_-Nd55YJMx3EItmsvUnsWijq/view?usp=sharing

**Comment by florianf22** [comment]
Hi, shifted the button a bit, it's looking better now

**Review by riha112 — APPROVED** [review]

**Pull request merged**
