### PR TITLE
#4078 - added loader in checkout guest form

### PR DESCRIPTION
**Pull request by florianf22**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4078

**Problem:**
* loader wasn't showing when signin via CheckoutGuestForm

**In this PR:**
* took advantage of the isLoading prop, displayed Loader if the form is loading

### CODE REVIEW

**Comment by Elena-Evsa** [comment]
Please, merge master to pr (there are bug presents on checkout which is fixed on master already)

**Comment by florianf22** [comment]
master up to date

**Comment by zans-laksa** [comment]
@florianf22  You have added extra space for almost every line.
Please fix that so we can see only modified lines and can check them.
image

**Comment by Elena-Evsa** [comment]
Loader absent https://vimeo.com/693957540/9d6990d206

**Comment by florianf22** [comment]
> @florianf22 You have added extra space for almost every line. Please fix that so we can see only modified lines and can check them. image

I see, sorry. I'll remove that now

**Comment by florianf22** [comment]
I'll close this PR and open again so that I can fix the git issue

**Comment by zans-laksa** [comment]
Actually, it's possible to remove the extra space from the file without making a new PR.

**Pull request closed without merging**
