### PR TITLE
Enable forbid rule on creating anchor tag. Remove unused component

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
**Problem:**
* Usual problem that I see on projects is developers using `<a>` tag instead of `<Link>`. This causes reloads of application which breaks concept of SPA. Of course some cases anchor tag is needed, but usually redirects goes within application so for specific case we can just set to ignore rule.

### CODE REVIEW

**Comment by AleksandrsKondratjevs** [comment]
@zans-laksa What do you it? If it makes sense and will it be good to have such rule enabled?
I think it is basic of react to use router links, but we can't supervise all and from my own experience this case is very often present. 

Cons of it is that there should be comment which disables this rule for following lines where `<a>` tag needed.

**Comment by AleksandrsKondratjevs** [comment]
Mo to CSA only.

**Comment by zans-laksa** [comment]
1. But why did you close it? :)
2. Please leave it for SPWA too, since devs can forget about the necessity of using `<Link>` instead of `<a>`.
3. Please give a better message. Start it with the capital letter, end it with a dot. Something like this could fit: "Use the \<Link\> component instead of \<a\>."

**Comment by AleksandrsKondratjevs** [comment]
> 1. But why did you close it? :)
> 2. Please leave it for SPWA too, since devs can forget about the necessity of using `<Link>` instead of `<a>`.
> 3. Please give a better message. Start it with the capital letter, end it with a dot. Something like this could fit: "Use the <Link> component instead of <a>."

Hmm, though that actually we just won't let to use `<a>` here. So in source it is not common case and if override on extended theme, then only add comment to ignore it. Anyway just thinking it will be more clear out here.
What you think about it?

**Review by ejnshtein — APPROVED** [review]

**Pull request merged**
