### PR TITLE
Pass if product alerts enabled to component and adjust stylings

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Size is different for 'Notify me...' in different browsers
**Steps**
1. Open PDP in Chrome
2. Open PDP in Safari

**Actual result:**
Safari: Size is 11px
Chrome: Size is 13.333px
Screenshot 2021-08-23 at 10 14 37
Screenshot 2021-08-23 at 10 16 07

**Expected result:**
Size for text is 14px in all browsers

+I don't receive email when price drops or product is in stock

**Comment by aleksandrakorolova** [comment]
Also, hover effect is missing

**Comment by Elena-Evsa** [comment]
**Issue 1:** Size is different for 'Notify me...' in different browsers - **Fixed**
Chrome: 14 px
Opera: 14 px
Firefox: 14 px
Safari: 14 px
**Issue 2:** I don't receive email when 
- price drops - **Not fixed** - still don't receive email
- product is in stock - **Not fixed**
To reproduce set up Product Alert Run Settings
**Issue 3:** hover effect is missing - **Fixed**
**Issue 4:** Link is displayed on the left side if we use RTL layout - **Can not check**, only on pmrev
**Issue 5:** Line overlaps to links in mobile layout - **Fixed**

**Comment by riha112** [comment]
FYI you can open inspect element and change `dir="ltr"` in `html` to `dir="rtl"` to test RTL layout
image

**Comment by Elena-Evsa** [comment]
Great advice, thanks @riha112 
Issue 4: fixed

**Review by zans-laksa — APPROVED** [review]

**Pull request merged**
