### PR TITLE
Bugfix #2308 - Green frame for qty field on product page

### PR DESCRIPTION
**Pull request by vladi-j**
Issue: #2308 

Quantity field's frame is not turning green anymore.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Green frame stays for grouped products 
https://pr-2336.d25kd40decjpue.amplifyapp.com/default/22-group.html
image

And bundle product
https://pr-2336.d25kd40decjpue.amplifyapp.com/default/bundle-dress.html
image

**Comment by vladi-j** [comment]
Fixed. Now the styling is more general.

**Comment by aleksandrakorolova** [comment]
Field frame doesn't become green when entering text in text field for simple product with customization 
https://pr-2336.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
Actual result:
image

Expected result:
image

**Comment by vladi-j** [comment]
Specified styling only for input type number.

**Review by ejnshtein — APPROVED** [review]

**Pull request merged**
