### PR TITLE
#4261 - fixed text overflowing on second line on small devices

### PR DESCRIPTION
**Pull request by florianf22**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4261

**Problem:**
* The problem was that when going on small devices, terms and conditions text were stretching on two lines and so did the '-' symbol.
* 
**In this PR:**
* on mobile devices, removed '-' and added margin left to the read more button so it's moved right now. Because I can't define breakpoints and the way html is set up, I can't position '-' on the tablet and mobile devices correctly, I need one more breakpoints, otherwise it's not possible.

### CODE REVIEW

**Comment by florianf22** [comment]
it'll look like this on desktop devices
image

and like this on mobile and tablet
image
image

**Comment by aleksandrakorolova** [comment]
1. Symbol '-' is missing between 'I agree to terms and conditions' and 'read more'
2. Mobile/Tablet: Read more is shifted right
Screenshot 2022-03-22 at 12 59 06
**Expected result:**
Screenshot 2022-03-22 at 13 01 33

**Comment by florianf22** [comment]
Corrected

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. Fixed
3. Can reproduce issue from task
Screenshot 2022-03-24 at 08 55 12

**Comment by florianf22** [comment]
is this okay? it'll work normally on bigger screens
image

**Comment by aleksandrakorolova** [comment]
No, it should be like this 
Screenshot 2022-03-25 at 08 48 20

**Pull request closed without merging**
