### PR TITLE
#2953 - shipping step issues

### PR DESCRIPTION
**Pull request by tatiana-scandi**
Issues: https://github.com/scandipwa/scandipwa/issues/2953, https://github.com/scandipwa/scandipwa/issues/2954, https://github.com/scandipwa/scandipwa/issues/2955

- Fixed the issue of unavailable shipping code selected by default
- Fixed the issue of selected shipping code lost when going to billing step and back to shipping
- Fixed default country not to be set correctly on page load
- Fixed regions not to be selected when default country is country with regions

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
**Steps:**
1. Register user or log in with existing user but she/he shouldn't have saved addresses
2. Add product to cart
3. Open Shipping step
4. Click on Proceed to billing

**Actual result;:**
Internal server error appears
debugMessage: "Notice: Undefined index: shipping_carrier_code in /var/www/public/vendor/scandipwa/quote-graphql/src/Model/Resolver/SaveAddressInformation.php on line 123"
Screenshot 2021-07-22 at 09 19 46

**Expected behavior:**
Shipping address form is opened

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova I made shipping address form to open expanded, if user has no saved addresses. Please, recheck.

**Review by zans-laksa — APPROVED** [review]
Code review passed.

**Comment by carinadues** [comment]
These fixes were merged in https://github.com/scandipwa/scandipwa/pull/2981

**Pull request closed without merging**
