### PR TITLE
Remove Braintree payment method from theme

### LINKED ISSUE #2142: Braintree as extension for ScandiPWA
**Description**:
Remove Braintree from core ScandiPWA theme and make it as extension with implemented vault-storage.

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
fixes #2142 
Remove braintree payment method from theme and make it as extension

Related PR:
https://github.com/scandipwa/braintree-graphql/pull/1

### CODE REVIEW

**Comment by teodormoq** [comment]
You forgot to remove the npm package called `braintree-web-drop-in`

**Comment by AleksandrsKondratjevs** [comment]
> You forgot to remove the npm package called `braintree-web-drop-in`

Oh, yes, you right, thanks!

**Comment by yeegor** [comment]
Please make sure that all of the braintree-related packages are removed from the `@scandipwa/scandipwa` monorepo's dependencies.
image

**Review by yeegor — CHANGES_REQUESTED** [review]
See comment above

**Comment by AleksandrsKondratjevs** [comment]
> See comment above

Hello!
Removed braintree packages from yarn locks and also dependencies from it: credit-card-type, framebus and etc.

**Review by yeegor — APPROVED** [review]
Nois

**Pull request merged**
