### PR TITLE
Support translations inside of plugins

### PR DESCRIPTION
**Pull request by yeegor**

### CODE REVIEW

**Comment by robertsbriedis** [comment]
Looks good.

**Comment by alfredsgenkins** [comment]
I wonder if we should close this for now and migrate into `create-scandipwa-app`?

**Comment by yeegor** [comment]
I think this should of course be migrated to the CSA, but nothing stops us from releasing this in the closest time in this repo.

**Comment by alfredsgenkins** [comment]
Implemented in Create ScandiPWA App

**Pull request closed without merging**
