### PR TITLE
My Account refactoring

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
**Related PR(s)**
* https://github.com/scandipwa/customer-graph-ql/pull/20

**Problem:**
* Need  to refactor My account

**In this PR:**
* My account refactoring

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1.Wrong URL for Address book

**Steps:**
1. Open FE
2. Log in
3. Open Address book

**Actual result**
URL - https://pr-3485.d25kd40decjpue.amplifyapp.com/default/customer/account/address

**Expected result:**
 https://pr-3485.d25kd40decjpue.amplifyapp.com/default/customer/address/
 ___________________
 2.Error and success message appear + product disappears then it appears and disappears again when adding product to cart from wishlist 
 
 **Steps:**
1. Open FE
2. Log in
3. Open PDP with required options
4. Add to wishlist
5. Open Wishlist
6. Click on Add to cart

**Actual result**
Error and success message appear + product disappears (sometimes then appears and disappears again)
https://drive.google.com/file/d/16w-8swcp4Rtrk4nkuq439pbibFVQtSKx/view?usp=sharing

**Expected result:**
Error message appears and user redirects to PDP
_______________________________
3.Old email is displayed in my account after changing email

**Steps:**
1. Open FE
2. Log in
3. Open Account information page
4. Select checkbox 'Change email'
5. Enter new email
6. Confirm current password
7. Click on Save

**Actual resuL**
User sees success message and he/she redirects to My account page and old email is displayed
https://drive.google.com/file/d/1z4elVlEci1I2pZK7evTIJyLOG1b2Wk_Z/view?usp=sharing

**Expected result:**
User logs out as default magenta
User can log in only with new email

**Notes:**
User sees new email in my account if he/she logged ount and loghed in with new email
_____________________
4.Error message 'Minimum 8 characters!' is displayed when subbmitting empty form

**Steps:**
1. Open FE
2. Log in
3. Open Account information page
4. Select checkbox 'Change password'
5. Click on Save

**Actual result:**
Error messages 'This field is required!' and 'Minimum 8 characters!' are displayed below Confirm password form
Screenshot 2021-10-08 at 10 20 39

**Expected result**
Error message 'This field is required!' is displayed below each empty required field
Screenshot 2021-10-08 at 10 23 40
______________________
5.Placeholder for 'Confirm New Password' field is missing

**Steps:**
1. Open FE
2. Log in
3. Open Account information page
4. Select checkbox 'Change password'

**Actual result:**
Placeholder for 'Confirm New Password' field is missing
Screenshot 2021-10-08 at 10 30 07

**Expected result:**
Placeholder 'Retype your password' is displayed in 'Confirm New Password' field
________________________
6.Email and prssword are written in wrong field if user selects/unselects checkboxes 'Change email' or 'Change password'

**Steps:**
1. Open FE
2. Log in
3. Open Account information page
4. Select 'Change email' checkbox
5. Select 'Change password' checkbox
6. Enter Password
7. Enter New Password
8. Enter Confirm new Password
9. Unselect 'Change email' checkbox

**Actual result:**
Email is written in Password field
Password is written in New password field
New password is written in Confirm new password field
Confirm new password field is empty
https://drive.google.com/file/d/1YIJo8tmniHweTytrYBNy0AZgFPtmv8KQ/view?usp=sharing

**Expected result**
Password is written in Password field
New password is written in New password field
Confirm new password is written in Confirm new password field
__________________________
7.Written email and password don't saved if user unselected and then selected again checkbox again 

**Steps:**
1. Open FE
2. Log in
3. Open Account Information page
4. Select 'Change email' checkbox
5. Change email
6. Unselect checkbox
7. Select checkbox again
8. The same do with 'Change password' checkbox and password field

**Actual result:**
Written email and password don't saved 
https://drive.google.com/file/d/1un9wyzuHdcNesQDxWbYOaWqS9fb68bIV/view?usp=sharing

**Expected result:**
Written email and password are saved as defaul Magenta
____________________________
8.Button 'Save changes' is shifted down on Newsletter page

**Steps:**
1. Open FE
2. Log in
3. Open newsletter page

**Actual result:**
Button 'Save changes' is shifted down
Screenshot 2021-10-08 at 11 18 06

**Expected result:**
Button is looks like in screenshot
Screenshot 2021-10-08 at 11 18 00
____________________________
9.Wrong URL for Newsletter page

**Steps:**
1. Open FE
2. Log in
3. Open Newsletter block

**Actual result**
URL - https://pr-3485.d25kd40decjpue.amplifyapp.com/default/customer/account/newsletter-subscription

**Expected result:**
 https://pr-3485.d25kd40decjpue.amplifyapp.com/default/newsletter/manage/
_____________________________
10. Mobile: Big indent between the last field and button Save on Account information page

**Steps:**
1. Open FE
2. Log in
3. Open Account information 
4. Select checkbox

**Actual result:**
Big indent between the last field and button Save
Screenshot 2021-10-12 at 13 22 31

**Expected result:**
It looks like Address form
Screenshot 2021-10-12 at 12 33 51
__________________________________
11. Error message is displayed twice in Reset password form when submitting invalid password 

**Steps:**
1. Open FE
2. Open Forgot password form
3. Enter Email
4. Submit
5. Open reset password link in email
6. Enter password using one class of characters or <5 characters
7. Click on Update password

**Actual result:**
Error message is displayed twice 
Screenshot 2021-10-12 at 12 47 47

**Expected result:**
No duplicate
_________________________
12. Wrong confirm link is sent in email

**Steps:**
**Admin panel:**
1. Open Admin panel -> Sores -> Configuration -> Customer -> Custome Configuration
2. Set Require Emails Confirmation to yes
3. Save
4. Clear Cache

**FE:**
1. Open FE
2. Open Create account form
3. Fill form
4. Submit
5. Open confirm link in email
or open https://pr-3485.d25kd40decjpue.amplifyapp.com/default/account/confirm/?email=aleksandra005%40scandiweb.com&key=MTjP2nE1oxqqEMZ2JSFquC0G3HHhdF3g

**Actual result:**
404 page

**Expected result:**
Confirm link opens

**Link:**
In email: https://pr-3485.d25kd40decjpue.amplifyapp.com/default/account/confirm/?email=aleksandra005%40scandiweb.com&key=MTjP2nE1oxqqEMZ2JSFquC0G3HHhdF3g

Link opens: https://pr-3485.d25kd40decjpue.amplifyapp.com/customer/account/confirm/?email=aleksandra005%40scandiweb.com&key=MTjP2nE1oxqqEMZ2JSFquC0G3HHhdF3g

Also, please merge changes from master (fixes for address form and wishlist)

**Comment by AleksandrsKondratjevs** [comment]
@aleksandrakorolova Hello!
Can you recheck please ? Also, last one issue is only with BE changes that added into PR description

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. 
3. Please, change the notification message to 'You saved the account information.' as in default Magento
**Actual result:**
Screenshot 2021-10-13 at 09 03 58
**Expected result:**
Screenshot 2021-10-13 at 09 07 22
4. Now this message is displayed below New password form 
Screenshot 2021-10-13 at 09 07 28
5. Fixed 
6. Fixed
7. Not Fixed
8. Fixed
9. Fixed 
10. Fixed 
11. Fixed
12. Ok
13. Error message is missing on reset password page when submitting invalid password if before it user submitted not match passwords 

**Steps:**
1. Open FE
2. Open Forgot password form
3. Enter Email
4. Submit
5. Open reset password link in email
6. Enter password using one class of characters 
7. Click on Update password
8. Change confirm password (enter another password)
9. Click on Update password
10. Confirm password (Enter the same password using one class of characters)
11. Click on Update password

**Actual result:**
Error message is missing
https://drive.google.com/file/d/1s7WyN3e5C5jQWbHDRfFIBg0K7DnJadnB/view?usp=sharing
Also, Wrong error in 9step
**Expected result:**
Error message appears

14.

**Comment by aleksandrakorolova** [comment]
4.Fixed
14.Still can reproduce
15.Fixed

**Comment by Elena-Evsa** [comment]
16. Ooops page appear if user open link that leads to page in account (https://pr-3485.d25kd40decjpue.amplifyapp.com/default/customer/account). User should be redirected to Login page
image

**Comment by aleksandrakorolova** [comment]
14.Fixed
16.Page looks ugly when opening https://pr-3485.d25kd40decjpue.amplifyapp.com/default/customer/account pages
Screenshot 2021-11-16 at 13 27 04
**Expected result:**
User redirects to /customer/account/login/ page

**Comment by aleksandrakorolova** [comment]
16. Fixed for /customer/account and /customer/account/edit 
Please, fix all pages for my account:
https://pr-3485.d25kd40decjpue.amplifyapp.com/default/sales/order/history
https://pr-3485.d25kd40decjpue.amplifyapp.com/default/downloadable/customer/products
https://pr-3485.d25kd40decjpue.amplifyapp.com/default/wishlist
https://pr-3485.d25kd40decjpue.amplifyapp.com/default/customer/address
https://pr-3485.d25kd40decjpue.amplifyapp.com/default/newsletter/manage

**Review by ejnshtein — APPROVED** [review]

**Pull request merged**
