### PR TITLE
2944/standalone mode detection

### PR DESCRIPTION
**Pull request by tatiana-scandi**
Issues: https://github.com/scandipwa/scandipwa/issues/2941 + https://github.com/scandipwa/scandipwa/issues/2944

Standalone mode worked fine when ScandiPWA is deployed as Magento theme (like there: http://scandipwapmrev.indvp.com/). So the problem was only in development. The reason for this is that different `index.html` files were used. So I adjusted index.html used in storefront mode to be able to support standalone mode as well.

Also fixed issue with Add to Home banner screen being shown in Chrome.

### CODE REVIEW

**Review by zans-laksa — APPROVED** [review]
Code review passed.

**Comment by aleksandrakorolova** [comment]
#2941 - fixed
#2944 - ScandiPWA logo is not present  for icon on Home screen 
https://drive.google.com/file/d/1mRL9s8Xr0ez04z5AhSnkvpphOPZy3ky7/view?usp=sharing
+Banner is displayed on FF
IMG_0081

**Comment by tatiana-scandi** [comment]
Issue with FF - fixed.
Issue with missing icon - need more details how to reproduce. Not yet fixed.

**Comment by aleksandrakorolova** [comment]
Banner in FF - fixed
I tested on iPhone 7 iOS12 (real device). Also, I checked in different devices (iPhone 12 iOS14, iPhone XS iOS 13 and 12) in BrowserStack  - I can't save it in BrowserStack but window Add to home screen opens and there is no Logo
Screenshot 2021-08-03 at 07 55 14

**Comment by tatiana-scandi** [comment]
Issue with missing icon - fixed. 
The problem turned out to be how Amplify build works - icon in nested folder was not collected and request that should have returned an icon returned 404.

**Pull request merged**
