### PR TITLE
#3701 - Getting cart using default magento functions

### PR DESCRIPTION
**Pull request by IrinaZhadzinets**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3701

**Includes:**
* https://github.com/scandipwa/quote-graphql/pull/99
* https://github.com/scandipwa/quote-graphql/pull/101

**Problem:**
* Getting cart with scandiPWA functions

**In this PR:**
* Getting cart with magento default functions

### CODE REVIEW

**Review by zans-laksa — APPROVED** [review]

**Comment by aleksandrakorolova** [comment]
Сart is empty after adding product to cart:

- Guest: Cart token changes after adding product to cart 
- Logged in user: Created new cart with the same token after adding product to cart 

https://vimeo.com/731278578/edc51908b2
Logs:
```[2022-07-19T08:15:39.628800+00:00] main.ERROR: Cannot query field "applied_rule_ids" on type "CartPrices". Did you mean "applied_taxes"?

GraphQL (1:77)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                               ^
 [] []
[2022-07-19T08:15:39.630650+00:00] main.ERROR: Cannot query field "coupon_code" on type "CartPrices".

GraphQL (1:94)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                                                ^
 [] []
[2022-07-19T08:15:39.631627+00:00] main.ERROR: Cannot query field "quote_currency_code" on type "CartPrices".

GraphQL (1:106)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                                                            ^
 [] []
[2022-07-19T08:15:39.632551+00:00] main.ERROR: Cannot query field "percent" on type "CartTaxItem".

GraphQL (1:344)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                                                                                                                                                                                                                                                                                                          ^
 [] []
[2022-07-19T08:15:39.633760+00:00] main.ERROR: Cannot query field "amount_incl_tax" on type "SelectedShippingMethod".

GraphQL (1:512)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ^
 [] []
[2022-07-19T08:15:39.634489+00:00] main.ERROR: Cannot query field "tax_amount" on type "SelectedShippingMethod". Did you mean "amount"?

GraphQL (1:580)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^
 [] []
[2022-07-19T08:15:39.635629+00:00] main.ERROR: Cannot query field "minimum_order_amount" on type "Cart".

GraphQL (1:631)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^
 [] []
[2022-07-19T08:15:39.636275+00:00] main.ERROR: Cannot query field "sku" on type "CartItemInterface".

GraphQL (1:721)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ^
 [] []
[2022-07-19T08:15:39.636988+00:00] main.ERROR: Cannot query field "is_in_store_pickup_available" on type "Cart".

GraphQL (1:1874)
1: query($cart_id_1:String!){cartData:cart(cart_id:$cart_id_1){id,email,prices{applied_rule_ids,coupon_code,quote_currency_code,grand_total{value,currency},subtotal_including_tax{value,currency},subtotal_excluding_tax{value,currency},subtotal_with_discount_excluding_tax{value,currency},discount{label,amount{value,currency}},applied_taxes{label,percent,amount{value,currency}}},shipping_addresses{available_shipping_methods{available,method_code,carrier_code,carrier_title,error_message},selected_shipping_method{amount_incl_tax,carrier_code,carrier_title,method_code,method_title,tax_amount,amount{value,currency}},customer_notes},minimum_order_amount{minimum_order_amount_reached,minimum_order_description},items{id,uid,sku,quantity,product{uid,id,sku,name,type_id,stock_status,url,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},... on ConfigurableProduct{configurable_options{attribute_code,values{value_index}},variants:variants{product{id,sku,stock_status,salable_qty,stock_item{in_stock,min_sale_qty,max_sale_qty,qty_increments},thumbnail{path,url},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label}}}},attributes:s_attributes{attribute_id,attribute_value,attribute_code,attribute_label,attribute_options{label,value,swatch_data{type,value}}},product_links{position,link_type,linked_product_sku}},prices{price{value,currency},row_total{value,currency},row_total_including_tax{value,currency},total_item_discount{value,currency}},... on DownloadableCartItem{links{id,title,sort_order,price},samples{id,title}},... on BundleCartItem{bundle_options{id,label,type,values{id,label,quantity,price}},customizable_options{id,label,label,type,sort_order,is_required,values{id,label,value}}},... on ConfigurableCartItem{configurable_options{id,option_label,value_label}}},total_quantity,is_virtual,is_in_store_pickup_available}}```

**Comment by aleksandrakorolova** [comment]
1. Product options (customization option, links) are missing in the cart
Screenshot 2022-07-20 at 11 50 39
______________
2.  Button + isn't disabled for product if user added all available product to cart
Screenshot 2022-07-21 at 14 47 26 (2)
______________
3. Error message 'The requested qty exceeds the maximum qty allowed in shopping cart' appears when adding product to cart for specific user
**Steps:**
- Open Sign in form
- Log in with user asd@asd.asdd/Scandipwa123
- Open PDP
- Add product to cart

```Cannot use object of type Magento\Framework\GraphQl\Exception\GraphQlInputException as array```

Screenshot 2022-07-21 at 16 39 50 (2)
______________
 4.Internal server error message appears when logging in if guest had the same product with the same options as logged in customer
**Steps:**
- Open Sign in form
- Log in with user X
- Open PDP with bundle or customizable options
- Add product to cart
- Log out 
- Open the same PDP
- Select the same Options
- Open Sign in form
- Log in with the same user

https://vimeo.com/732356666/b605d5a47e

[2022-07-22T06:02:30.759873+00:00] main.ERROR: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in /var/www/public/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108
GraphQL (1:68)
1: mutation($source_cart_id_1:String!,$destination_cart_id_1:String!){mergeCarts(source_cart_id:$source_cart_id_1,destination_cart_id:$destination_cart_id_1){id}}
______________
5. Logged in users (General customer group) can apply cart price rule for Not Logged in users
**Steps:**
- Open Sign in form
- Log in with user from General customer group
- Open PDP 
- Add product to cart (price should be >500$)
- Open Cart 
- Enter Coupon Code '**500**'
- Submit it

**Actual result:**
Success message 'Coupon was applied!' appears and discount is applied

**Expected result:**
Error message 'The coupon code isn't valid. Verify the code and try again.' appears
______________
6. Discount amount isn't updated after user selected shipping address if Cart price rule is applayed to shipping delivery too
**Steps:**
- Open PDP
- Add product to cart
- Open Cart
- Enter coupon code '**50off**'
- Go to shipping step
- Fill shipping form
- Select Shipping method
- Go to billing step

**Actual result:**
Discount amount isn't recalculated after selecting shipping delivery
Screenshot 2022-07-22 at 12 55 10

**Expected result:**
Discount amount is recalculated after selecting shipping delivery
______________
in progress...

**Comment by aleksandrakorolova** [comment]
4. Created separatle task for this issue #5076
5. It happens because of #5058

**Comment by IrinaZhadzinets** [comment]
2. Need add PR: https://github.com/scandipwa/quote-graphql/pull/101/files for this changes

**Review by zans-laksa — APPROVED** [review]

**Comment by Elena-Evsa** [comment]
9. Cart contain 0 products after update of status of product and refresh 
**Steps:**
1.Add 'In stock' product to cart
2.Open cart
Open admin:
3.Open product from step 2
4.Change 'Source Item Status' = out of stock
5.Save
Open FE tab:
6.Switch between pages
7.Open cart
8.Refresh cart

**Video:**
https://vimeo.com/734381930/af65e0129e

**Actual result:** 
Step 6 - cart contain products 
Step 8 - cart contain 0 products

**Expected result:** 
Step 8 - cart contain all products from step 7

**Comment by Elena-Evsa** [comment]
1. Failed: 
Customizable options names are absent in cart
https://pr-5021.d25kd40decjpue.amplifyapp.com/default/test-config-costomizable.html
https://pr-5021.d25kd40decjpue.amplifyapp.com/default/mouse-file-field.html
https://pr-5021.d25kd40decjpue.amplifyapp.com/default/mouse-text-field.html
https://pr-5021.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
image

**Comment by Elena-Evsa** [comment]
1. **Fixed**
2. **Fixed**
3. **Fixed**
4. Task created
5. Related task present
6. **Fixed**
8. **Fixed**
9. Task created

**Review by zans-laksa — APPROVED** [review]

**Pull request merged**
