### PR TITLE
#4498 - fixed select on safari mac

### PR DESCRIPTION
**Pull request by florianf22**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4498

**Problem:**
* Safari: Dropdown closes gradually on PDP

**In this PR:**
* added -webkit-appearance: none; to the select element.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1. Safari: looks better than it was but also, dropdown closes gradually 
2. The same issue appears on other browsers
https://drive.google.com/file/d/12vkIjGSDaA90bHO0XMvYBqKeF31-iXRv/view?usp=sharing

**Comment by florianf22** [comment]
Do you want to remove transitions at all? it has been removed now, please check

**Comment by aleksandrakorolova** [comment]
1. Still, can reproduce issue from task
2. Fixed

**Comment by florianf22** [comment]
Could you please clear cache? I can't reproduce it. After removing transition, select closes immediately on all browsers. I tested each and every safari on https://live.browserstack.com/ , same on my mac and my iphone

**Comment by aleksandrakorolova** [comment]
Yes, looks like cache. Now I also can't reproduce

**Comment by florianf22** [comment]
Great :-)

**Review by AleksandrsKondratjevs — APPROVED** [review]

**Pull request merged**
