### PR TITLE
[4165] background is visible on scroll fix

### PR DESCRIPTION
**Pull request by Mohamed-halim-sw**
**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4165

**Problem:**
* background can be seen behind navbar and sticky button on scroll, it can be fixed by removing the transition attribute.

**In this PR:**
* CategoryFilterOverlay.style.scss
	* line32 removed transition style

* NavigationTabs.style.scss
	* line 30 removed transition style

### CODE REVIEW

**Comment by Elena-Evsa** [comment]
1. Background is not blinking now, but menu hiding and appear immediately, can you make it smooth as on master?
1 part of video - pr
2 part - master
https://drive.google.com/file/d/1kza8qSRykeUeKZnggmaqoXiUpIu7uwmN/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Background is blinking when user scroll page with filter and browser's adress bar shown / hided
https://drive.google.com/file/d/1l_pcAoOEheg4VSxi4fWh9lQCJpqysU2y/view?usp=sharing

**Comment by Elena-Evsa** [comment]
1. Still have this issue if user scroll down till the end https://drive.google.com/file/d/1m1zLqf3wMls5zpgY9-VXUOSPdTjtK3OS/view?usp=sharing
2. PDP - passed
Confirm delete - still present - https://drive.google.com/file/d/1lzS4WibFhfjLH5KUrUr8SBvXUqs8R3Oq/view?usp=sharing
Wishlist - passed
3. Can reproduce
4. Small part of image shown under the title on 'write a review' page
image

**Comment by Elena-Evsa** [comment]
1. Still have this issue if user scroll down till the end and toolbar of browser hiding / appears (Same with 'edite adrress')
2. PDP - passed
Confirm delete - still present 
Wishlist - passed
3. Can reproduce
4. Passed

**Comment by aleksandrakorolova** [comment]
1. Still, can reproduce - https://drive.google.com/file/d/1UpVQV-z6COledYS_j6x33fqHtyJHv0kh/view?usp=sharing
2. Confirm delete - still, can reproduce - https://drive.google.com/file/d/1UteePTD0n4tzWdpbpcn_R9WeWtnmI8Eu/view?usp=sharing
Edit address and add new address - https://drive.google.com/file/d/1UrCBb-rIm0I27jyy5p2LXAfPBwbsAm3l/view?usp=sharing
3. Still, can reproduce - https://drive.google.com/file/d/1cD5q_HHLqyjfGGt8dcp2weJ4lsX_-31i/view?usp=sharing

**Comment by aleksandrakorolova** [comment]
1-3. Still can reproduce all issues

**Comment by aleksandrakorolova** [comment]
1-3. Still can reproduce all issues
https://drive.google.com/file/d/1V8QimhPwcdWtWfOQpNunlBts3yFWdxIg/view?usp=sharing

**Comment by Mohamed-Ahmed711** [comment]
Hello, can you tell me what browser or program was used to reproduce the issues, I tried to reproduce them in my browser in the mobile view, but it worked fine with me and I couldn't reproduce them.

**Comment by aleksandrakorolova** [comment]
I could reproduce on real iOS and Android devices. Browsers - Chrome, Safari (Suppose in FF and Opera too - I can recheck when you will fix amplify)
Screenshot 2022-03-04 at 07 37 29

**Comment by Mohamed-Ahmed711** [comment]
Hello thank you, I managed to reproduce them on a real android device and I'm working on the fix.

**Comment by aleksandrakorolova** [comment]
1. Filters on PLP - **Fixed** 
2.1 Confirm delete - **Fixed**
2.2 Edit address and add new address - **Failed**. Can reproduce + can't see button 'Save address'/'Edit address' - https://drive.google.com/file/d/1Xgmr11KLX4wdKj1nICtlYmGvWOB9r11m/view?usp=sharing
2.3 Wishlist - **Fixed**
4. Write new review - **Failed**. Still, can reproduce on iOS - https://drive.google.com/file/d/1yTIzA6OeRUdOTl8XS8joEMFy3HKCdSlh/view?usp=sharing

**Comment by aleksandrakorolova** [comment]
**1.** Can reproduce on iOS
**2.1** Confirm delete - Failed on iOS
**2.2** Edit address and add new address:
    Scroll - failed on iOS
    Can't see button 'Save address'/'Edit address' - Fixed
    Unnecessary indent below 'Save address'/'Edit address' buttons
Screenshot 2022-03-08 at 08 51 31

**2.3** Wishlist - Fixed
**3.** Write new review - Failed. Still, can reproduce on iOS 
**4.** FF: Can't scroll Save address'/'Edit address.Write new review forms
**5.** FF: Share Wishlist popup isn't on full screen
Screenshot 2022-03-08 at 08 51 59

**Comment by aleksandrakorolova** [comment]
**1** Filter: 
Scroll - **Fixed**
FF: Can't see button 'See result'
**2.1** Confirm delete - **Failed** on iOS
**2.2** Edit address and add new address:
Scroll - **Failed** on iOS - https://drive.google.com/file/d/143OJTPdHtAQLynR-AF9vjRDN3Is_o--7/view?usp=sharing
Can't see button 'Save address'/'Edit address' - **Failed**. Can reproduce on FF - https://drive.google.com/file/d/1XqPF92EKcPjuT6VJaH37bsmCE7Ir2F7S/view?usp=sharing
Unnecessary indent below 'Save address'/'Edit address' buttons - **Fixed** 
3. Write new review - **Failed**. Still, can reproduce on iOS - https://drive.google.com/file/d/1_88LlY4KkW_zt9TZcQRotUlYC3LeCZSc/view?usp=sharing
4. FF: Can't scroll Save address'/'Edit address.Write new review forms - **Fixed**
5. FF: Share Wishlist popup isn't on full screen - **Fixed**

**Comment by aleksandrakorolova** [comment]
**1.** Scrolling the Filter: 
FF: Can't scroll pop-up
**2.1** Confirm delete page - Still can reproduce on iOS
**2.2** Edit address and add new address:
Scroll - Failed on iOS 
FF: Can't scroll pop-up
Button 'Save address' is cropped in Edit/Add new address
Screenshot 2022-03-22 at 15 10 28
**3.** Write new review: 
Still can reproduce: background is visible
Button 'Submit review' overlaps to field 'Review' on iOS

**4.** Still can reproduce: Can't scroll Save address'/'Edit address/Write new review form/Filters
**5.** Fixed
**6.** background is visible when scrolling Share Wishlist on iOS

**Pull request closed without merging**
