### PR TITLE
#3972 Search functionality throwing error if search word contains & (Fix failed QA) 

### PR DESCRIPTION
**Pull request by iman-sujamiko**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3972 (issue + failed QA comments)

**Problem:**
* `&` in URL is normally used for separating pairs of query params. It should be encoded if used as part of query param.
* Ooops page appears when searching '%' symbol Error message 'URIError: URI malformed' appears in the console
* Error messages 'Error fetching Product List Information!' and 'Error fetching Product List!' when searching '+' symbol

**In this PR:**
* Removed replacement of ' ' to '+', used URL encoding instead (which handles `&` in search param among other cases). 
* make + symbol to empty space and prevent redirect to search page 
* problem with encode % symbol need to change it manually

This is a reacreated PR from @tappiola https://github.com/scandipwa/scandipwa/pull/4191

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
'No result found!' is displayed in overlay when searching product name with & symbol 

**Steps:**
1. Open website
2. Enter 'Koala &' in the search line
3. Wait (Don't press enter)

**Actual result:**
'No result found!' is displayed in overlay
Screenshot 2022-02-02 at 10 40 46

**Expected result:**
Matched products are displayed

**Notes:**
Product is displayed on search result page if user pressed Enter on keyboard
Screenshot 2022-02-02 at 10 40 56

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. Ooops page when entering '%%' in the seach line and pressing 'Enter' on keyboard
Error message 'URIError: URI malformed' appears in the console
Screenshot 2022-02-03 at 10 39 44

3. Error message 'Error fetching Product List!' when entering '++' in the search line and pressing 'Enter' on keyboard
Screenshot 2022-02-03 at 10 40 37

4. Nothing happens when entering '+' in the search line and pressing 'Enter' on keyboard

**Comment by iman-sujamiko** [comment]
for numbers 3 and 4 (because it prevents no 3 to happen) still have not found the solution so I commit the no 2 solution early

Note numbers 3 and 4: plus (+) symbol is always read by the system as white space and it forbid to have empty or white space only value

**Comment by aleksandrakorolova** [comment]
2.Still, can reproduce if open search result page in incognito mode (or clear browser cache and open link)
**Link:** https://pr-4217.d25kd40decjpue.amplifyapp.com/default/search/%25%25

3 and 4 Error message 'Error fetching Product List!' when entering '++' or '+' in the search line and pressing 'Enter' on keyboard
Screenshot 2022-02-04 at 09 11 24 (2)

**Comment by iman-sujamiko** [comment]
> 2.Still, can reproduce if open search result page in incognito mode (or clear browser cache and open link) **Link:** https://pr-4217.d25kd40decjpue.amplifyapp.com/default/search/%25%25
> 
> 3 and 4 Error message 'Error fetching Product List!' when entering '++' or '+' in the search line and pressing 'Enter' on keyboard Screenshot 2022-02-04 at 09 11 24 (2)

I dunno if this can be counted as a solution or not I have tried it in the test server https://scandipwapmrev.indvp.com/default/search/%25%25, it's going well

**Comment by aleksandrakorolova** [comment]
2.Fixed
3-4. No. Please, find solution

**Review by riha112 — APPROVED** [review]

**Pull request merged**
