### PR TITLE
[3726] Sub menu spacing

### PR DESCRIPTION
**Pull request by Dagnija-Viktorova**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3726

**Problem:**
* Space between category text and end of the block is too small in sub menu

**In this PR:**
* Added bottom margin to the sub menu so that the space equals to 80px

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Indent 60px looks big. Please, can you change this space to 40px (see screenshot)
Screenshot 2021-12-06 at 09 56 47

**Comment by Dagnija-Viktorova** [comment]
I applied a fix (changed the size to 40px), could this please get retested?

**Comment by aleksandrakorolova** [comment]
Maybe better to do the same spacing as between category and subcategory
Screenshot 2021-12-06 at 11 26 35

**Comment by Dagnija-Viktorova** [comment]
Changed free space to 28px, could this get reviewed again?

**Comment by aleksandrakorolova** [comment]
Thanks. It looks better!

**Comment by Dagnija-Viktorova** [comment]
Could this get reviewed again? I solved merge conflict

**Review by AleksandrsKondratjevs — APPROVED** [review]

**Review by ejnshtein — APPROVED** [review]

**Pull request merged**
