### PR TITLE
#4135 My account url's added to routeMap

### PR DESCRIPTION
**Pull request by BrunoScorzafave**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4135

**Problem:**
* Menu icon is painted over in navigation bar when opening My account pages

**In this PR:**
* Create a reference to MyAccount URLs inside routeMap

### CODE REVIEW

**Comment by Elena-Evsa** [comment]
Issue 1: icon of menu highlighted if user open current order 
image

**Comment by AleksandrsKondratjevs** [comment]
Maybe there is a way to add them dynamically from MyAccount component property ? Like get it and parse into needed form then spread into routeMap

**Comment by BrunoScorzafave** [comment]
There is. I will implement this

**Review by carinadues — CHANGES_REQUESTED** [review]
Note: there will be changes here

**Pull request merged**
