### PR TITLE
[2574] Form re styling according to QA comments

### LINKED ISSUE #2574: Rating isn't identified as mandatory though it is required for submitting the review
**Description**:
The product rating isn't identified as mandatory for the user, but it is required for submitting the review. This means that the user can't just write a comment, he/she has to rate the product giving it 1-5 stars.

**Expected behavior**:
The user should have a visual indication that the rating is mandatory. The text "This field is required!" should be displayed below each row of stars when the user tries to send a review without rating the product. 

This is how it looks in Luma:

image

**To Reproduce**:
1. Open a product description page.
2. Scroll down until Reviews.
3. Click on 'Write a new review'.

**Actual results**:
When the user clicks on Submit Review, he/she isn't notified that the rating is also mandatory.

image

### PR DESCRIPTION
**Pull request by pablobentivengo**
**Related issue(s):**
* Fixes #2574

**Problem:**
* Margin between star and error message is 12px
* Margin between error message and next rate is missing
* Delete red/green line for stars

**In this PR:**
* Modified Product Review Form styling to fit specifications

**Related PRs:**
* #4095

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1. Margin above error message is missing
Screenshot 2022-02-11 at 09 05 17
**Expected result:**
Margin above error message is 6px as for error messages for fields Nickname, Summary, Review 
Screenshot 2022-02-11 at 09 05 03

**Notes:**
How it looks in iOS:

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. iOS: Error message overlaps to stars
Screenshot 2022-02-14 at 08 45 47

**Comment by pablobentivengo** [comment]
Not ready for testing

**Comment by aleksandrakorolova** [comment]
2. Fixed
3. Indent is missing between stars and rate name
Screenshot 2022-02-15 at 07 52 22
4. Error message overlaps to stars
Screenshot 2022-02-15 at 07 46 53

**Review by riha112 — APPROVED** [review]

**Pull request merged**
