### PR TITLE
#3780 - Create confirm newsletter subscription page

### PR DESCRIPTION
**Pull request by IrinaZhadzinets**
**Includes:**
* https://github.com/scandipwa/newsletter-graphql
* https://github.com/scandipwa/route717/pull/18

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3780

**Problem:**
* Nothing happens when confirming newsletter subscription

**In this PR:**
* The success/failed page opens for confirming newsletter subscription via email

### CODE REVIEW

**Review by zans-laksa — APPROVED** [review]

**Comment by aleksandrakorolova** [comment]
Still, can reproduce issue

**Review by zans-laksa — APPROVED** [review]

**Comment by aleksandrakorolova** [comment]
@neeeeecka Please, check PR and fix what went wrong
Screenshot 2022-08-26 at 16 01 53

**Comment by aleksandrakorolova** [comment]
Still, user redirects to homepage 
https://vimeo.com/744084417/ed35c85ed8

**Comment by aleksandrakorolova** [comment]
1. Please, change order of text
Screenshot 2022-08-30 at 14 47 21

2. Change styles for text on the second line:
- Remove **Bold**
- Only the first word is written with Capital letter
- Change font size to 14px as on Thank you page
Screenshot 2022-08-30 at 14 44 15
3. Please, add text 'The URL is invalid. Some parameters are missing.' on broken Confirm Subscription page as on the broken confirm account page

**Broken link:**
https://scandipwapmrevprtest-dev.indvp.com/default/newsletter/subscriber/confirm/id/234/code
**Actual result:**
Screenshot 2022-08-30 at 14 09 30
**Expected result:**
Screenshot 2022-08-30 at 14 09 37

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. Fixed
3. Fixed
4. Please, show title 'Confirm Subscription instead of logo on mobile
Screenshot 2022-09-02 at 15 44 59

**Comment by AleksandrsKondratjevs** [comment]
Closing due to deprecated code and no activity.

**Comment by AleksandrsKondratjevs** [comment]
Closing due to deprecated code and no activity.

**Pull request closed without merging**
