### PR TITLE
fixed text overflowing on second line on small devices

### PR DESCRIPTION
**Pull request by florianf22**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4261

**Problem:**
* The problem was that when going on small devices, terms and conditions text were stretching on two lines. instead of doing text-wrap: no wrap, decreased font size a bit so that it looks better

**In this PR:**
* changed font size by 1px .

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Please, don't do this. Move T&C from first line to second if it doesn't fin in one line

**Comment by aleksandrakorolova** [comment]
Still, can reproduce issue 
Screenshot 2022-03-08 at 12 30 29

**Comment by florianf22** [comment]
Did some changes

**Comment by aleksandrakorolova** [comment]
Still, can reproduce issue 
Screenshot 2022-03-11 at 14 55 55

**Pull request closed without merging**
