### PR TITLE
[4017] modified to render top border instead of bottom

### PR DESCRIPTION
**Pull request by pablobentivengo**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4017

**Problem:**
* Order product list last product rendered border bottom on mobile

**In this PR:**
* Modified Style to render border top instead

### CODE REVIEW

**Review by carinadues — APPROVED** [review]
Had already been approved by Rihards in #4173

**Comment by aleksandrakorolova** [comment]
Please, return line below the last product in Order Shipments if the Shipments comment was left. If no comments - don't need to display this line 
Screenshot 2022-02-02 at 12 10 51

**Comment by aleksandrakorolova** [comment]
Please, read carefully the previous comment. 
Conditions should be:
- If there is a comment, show the line after the last product
- If no comment, don't display the line after the last product

**Comment by aleksandrakorolova** [comment]
Please, add this logic for the desktop view too

**Review by riha112 — APPROVED** [review]

**Pull request merged**
