### PR TITLE
Fixed product description not shown if only image

### LINKED ISSUE #4480: Image is missing in the description on PDP if user added only image
**Description**:
Image is missing in the description 

**Expected behavior**:
Image is displayed in the description 

**To Reproduce**:
**Admin panel:**
1. Open Admin panel -> Go to Catalog -> Products 
2. Open Product
3. Add image in description (don't add text)
4. Save

**FE:**
1. Open PDP -https://scandipwapmrev.indvp.com/default/downloadable-e-reader.html

**Actual result**:
Image is missing in the description 

**Additional context**:
It's displayed on PDP if user added image and text

### PR DESCRIPTION
**Pull request by SalimMersally**
**Related issue(s):**
* Fixes #4480 

**Problem:**
* Description (About tab) was not shown if the description contains only an image
* state isInformationTabEmpty is true in this case

**In this PR:**
* Fixed the function isProductInformationTabEmpty to return false if HTML contain only image
* now about tab show even if it is only an image

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1. Image is missing if user added image via default editor but not via HTML code - https://pr-4566.d25kd40decjpue.amplifyapp.com/default/bundle-e-reader-with-dynamic-price.html
Screenshot 2022-03-25 at 10 15 18 (2)

**Comment by carinadues** [comment]
For who will do CR: please notice it didn't do the checks. Let us know if smth should be done about it.

**Review by AleksandrsKondratjevs — APPROVED** [review]

**Comment by aleksandrakorolova** [comment]
1. Still, can reproduce

**Comment by carinadues** [comment]
image

**Comment by aleksandrakorolova** [comment]
Sorry, Looks like cache. Now it is displayed for me too

**Pull request merged**
