### PR TITLE
SWPWA - Remove infinity slider if only 1 slide present

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**

### CODE REVIEW

**Comment by yeegor** [comment]
Please link the issue that this PR resolves.

**Review by yeegor — CHANGES_REQUESTED** [review]
I guess all the sliders should not move if they only contain 1 slide? What is the target behaviour of this PR?

**Comment by AleksandrsKondratjevs** [comment]
> I guess all the sliders should not move if they only contain 1 slide? What is the target behaviour of this PR?

Hey! Sorry for no describe issue and don't have link to issue (PM request). Just slider widget was infinite even if slider has only 1 slide. But expected behavior is:
If slider has only 1 slide then it should not be infinitive (only 1 slide present without repeating it). And only if slider is infinitive then set slide width to 80%, because if only 1 slide then need to be full width.

**Comment by yeegor** [comment]
Thanks for the explanation. My second comment is still relevant tho.

**Comment by AleksandrsKondratjevs** [comment]
> Thanks for the explanation. My second comment is still relevant tho.

Yes, if slider has only 1 slide then it should not move.

**Review by alfredsgenkins — APPROVED** [review]

**Pull request merged**
