### PR TITLE
#3965 Fixed dropdown opened

### PR DESCRIPTION
**Pull request by VanilStorm**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3965

**Problem:**
* Dropdown is closed for config product on PDP when clicking on disabled option

**In this PR:**
* Added a check for the dropdown list items.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1. Dropdown doesn't close when clicking outside dropdown
https://drive.google.com/file/d/1I_qQNmVcB8glSOzJLMzTfaxTJShVrZ1-/view?usp=sharing  
2. Scroll bar disappears for dropdown with many options. 
Screenshot 2022-03-16 at 10 25 03

**Comment by VanilStorm** [comment]
Sorry, but it seems to me that the second point is not my mistake. 
Nobody merge my PR, but here is the same mistake - ( https://master.d25kd40decjpue.amplifyapp.com/ )

**Comment by aleksandrakorolova** [comment]
Yes, you are right. Sorry, will create separate task for this issue
Please, fix the first point

**Comment by aleksandrakorolova** [comment]
1.Fixed
3.Dropdown doesn't close when selecting option (Clicking on option price)
https://drive.google.com/file/d/1PS1essgb_AujfuYskuNZi5RTpFWoXkAZ/view?usp=sharing

**Review by riha112 — APPROVED** [review]

**Pull request merged**
