### PR TITLE
[3972] modified the search query format

### LINKED ISSUE #3972: Search functionality throwing error if search word contains `&`
**Description**:
If searched word contains symbol `&` error is thrown.
`Error fetching Product List Information!`
`Error fetching Product List!`

 Also searching just `&` is thrown, searching for `/` - 404 page, `?` - 404 page.

Also same applies for search bar, just doesn't throw error, just doesn't display results. Under the hood I guess is happening same behaviour.
Dropdown:
`No results found!`

**Expected behavior**:
Found products to appear or if no products matching criteria, than no results page displayed.

**Screenshots, Video, Logs**
https://tech-demo.scandipwa.com/tech_storeview/search/Procter+&+Gamble

**To Reproduce**:
1. Go to any page.
2. Enter search word, ex: `Procter & Gamble`.
3. Press Enter.

**Versions**:
- ScandiPWA: 5.0.5^

### PR DESCRIPTION
**Pull request by pablobentivengo**
**Related issue(s):**
* Fixes #3972 

**Problem:**
* If searched word contains symbol & error is thrown.
Error fetching Product List Information!
Error fetching Product List!
Also searching just & is thrown, searching for / - 404 page, ? - 404 page.
* if sign / and ? goes first, 404 appear in console , but products shown - same for other special symbols
* if sign / goes in the middle of word, products not loaded 503 error in console - same for other special symbols

**In this PR:**
* Modified the string format before doing GRAPHQL Query.
* Created formatSearch function on Util/Common
* Function adds backslash to escape string for special characters in hex string

### CODE REVIEW

**Comment by pablobentivengo** [comment]
Also fixed searching for % and + or %% and ++. As well as only search for special characters

**Comment by Elena-Evsa** [comment]
1. Please, make the same behavior as on Luma for signs “[|]’~<!--@/*$%^&#*/()?>,.*/\  ♣ ☺ ♂

image

**Comment by pablobentivengo** [comment]
Tested on local with Local BE and search worked fine. Spoke to Aleks and decided to check if restarting PMREV and Master SV will fix issue.

**Comment by pablobentivengo** [comment]
Closing because actual error is on BE, and solution proposed in PR is not efficient.

**Pull request closed without merging**
