### PR TITLE
#3641 Home page opens if user click on name of search query in breadrums on search page

### PR DESCRIPTION
**Pull request by mahmoudwaliedScandiweb**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3641

**Problem:**
* search query name redirects to home.

**In this PR:**
* make "pointer-event" to last child of breadcrumb unclickable

### CODE REVIEW

**Comment by Elena-Evsa** [comment]
Failed:
1. If user click on Home in breadcrumbs then user should be redirected to homepage
2. If user click on search query in breadcrumbs then URL shouldn't be changed
https://vimeo.com/642623170/3d120c825e

**Comment by Elena-Evsa** [comment]
1. Failed - URL of home page https://pr-3693.d25kd40decjpue.amplifyapp.com/default/search/color?color shown again for search query Color
image
2. Passed

**Review by zans-laksa — CHANGES_REQUESTED** [review]
All elements in the project should be consistent.
Please check breadcrumbs in products or categories.
The last breadcrumb item has a link that matches the current page URL and pointer events are not disabled.
I believe, on a search page, it should be the same.
Your commit will affect all breadcrumbs on all pages and will make the last element not accessible.
@Elena-Evsa is this desired?

**Comment by Elena-Evsa** [comment]
@zans-laksa The last position in breadcrumbs (name of page where user situated) shouldn't have a hover effect, even cursor should look like pointer but not finger. So when it was fixed on Search page, I think, automatically it was fixed on PDP and other. But we have separate task for it #3545 and hover effect
When I marked task as QA Passed breadcrumbs worked like expected after this fix
Should I check this PR again after creating new amplify?

**Comment by zans-laksa** [comment]
@Elena-Evsa Good, got it!

**Review by zans-laksa — APPROVED** [review]

**Pull request merged**
