### PR TITLE
#3248 - no go back after popup close

### PR DESCRIPTION
**Pull request by tatiana-scandi**
Issue: https://github.com/scandipwa/scandipwa/issues/3248

There is difference between closing popup via hitting BACK button in browser and closing popup via click on Cross button, click outside or Escape key.

In first case we subscribe to `popstate` event. Popstate event  is fired when the active history entry changes while the user navigates the session history ( = so it occurs naturally).
```
window.addEventListener('popstate', this.hidePopUp);
```

When we close popup in some other ways, we also need to go back through history one step.

### CODE REVIEW

**Review by zans-laksa — APPROVED** [review]

**Comment by aleksandrakorolova** [comment]
Can reproduce with New Version Available pop-up 
**Steps:**

1. Open FE
2. Wait when New Version Available pop-up appears
3. Click on Dimiss 
4. Click on Back

**Actual result:**
User stays on the same page
https://drive.google.com/file/d/1qFBtSoWQiO70uzYG6CJlyV70I9XX7Q1w/view?usp=sharing

**Expected result:**
User redirects to previous page

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova please recheck dismiss button click case

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi I can't check it because PR doesn't have URL for testing

**Comment by tatiana-scandi** [comment]
@vromash could you please suggest what to do for amplify build to be triggered for this PR? It hasn't been triggered on PR creation for some reason.

**Pull request merged**
