### PR TITLE
2013 wrong password validation error

### PR DESCRIPTION
**Pull request by winniepukki**

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
**Description:**
Can't change password in confirm password field if user made mistake in password confirmation

**Expected behavior:**
User can change existing password (add 12)
Can enter password with more than 7 characters

**To Reproduce:**
1. Open website
2. Tap Account -> Tap Create account
3. Enter First name, last name, and valid not registered email
4. Enter password (Scandipwa12)
5. Confirm password (Scandipwa)
6. Tap Create account
7. Add 12 in the confirm password field (Should be Scandipwa12)

**Actual result:**
User can't add any symbols in confirm password field
User can't enter more than 7 characters in confirm password field If user deleted password and then he tried to enter again password (Scandipwa12)

**Review by yeegor — APPROVED** [review]
Seems fine

**Comment by yeegor** [comment]
I am not merging this so far, QA results are unknown yett.

**Comment by aleksandrakorolova** [comment]
Still can reproduce

**Comment by winniepukki** [comment]
Issue is still on the development stage. So far, this branch has not yet received [the following QA report improvements](https://github.com/scandipwa/scandipwa/pull/2047#issuecomment-755913359), as awaits an external branch merge with further code TO-DO. As soon as I complete the task, I will push all changes below here. Hope this helps! Cheers

**Review by alfredsgenkins — APPROVED** [review]

**Pull request merged**
