### PR TITLE
[4338] initialized current address values, set input values to current values

### LINKED ISSUE #4338: Name of state saved for field without dropdown when user selected other country
**Description**:
Name of state saved for field without dropdown when user selected other country

**Expected behavior**:
Input field stay free when user selected other country

**Screenshots, Video, Logs**
https://vimeo.com/680872899/d8770b8c3f

**To Reproduce**:
1. Open FE
2. Login in account with saved address with state as dropdown
3. Click account > Address book > Edite address
4. Change country (Albania) on country Afganistan

**Actual result**:
Name of state saved for field without dropdown when user selected other country

### PR DESCRIPTION
**Pull request by pablobentivengo**
**Related issue(s):**
* Fixes #4338 

**Problem:**
* Name of state saved for field without dropdown when user selected other country

**In this PR:**
* initialized current address values, set input values to current values

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. State isn't saved when save existing or new address 
https://drive.google.com/file/d/1ucetcefvhwbSLM-1-4KfehnU2Eebrfi3/view?usp=sharing
3. State is saved in dropdown when selecting 'Select country' option
Screenshot 2022-03-02 at 09 14 59

**Comment by aleksandrakorolova** [comment]
2. Fixed
3. Still, can reproduce

**Comment by aleksandrakorolova** [comment]
3. Still, can reproduce
https://drive.google.com/file/d/1xq8FFRUaCF7o6RXHUB6q6qJs75KGmVi3/view?usp=sharing

**Comment by pablobentivengo** [comment]
Closed PR because Amplify link was not generated.

**Pull request closed without merging**
