### PR TITLE
#2424 - mobile popup invalid top position

### PR DESCRIPTION
**Pull request by tatiana-scandi**
Issue: https://github.com/scandipwa/scandipwa/issues/2424

Caused by https://github.com/scandipwa/scandipwa/issues/2397, the fact that mobile popup should be placed just below the header was missed out.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Can reproduce this issue #2397
Mobile: only if new version pop-up appears
Screenshot_20210408-134556_Chrome

**Comment by tatiana-scandi** [comment]
Should be fine now:
ScandiPWA 2021-04-09 15-57-06
ScandiPWA 2021-04-09 15-56-41

**Comment by aleksandrakorolova** [comment]
iOS: White line with back button is displayed instead of logo on the homepage
**Steps:**
1. Open https://pr-2437.d25kd40decjpue.amplifyapp.com/ on iOS

**Actual result:**
Logo is missing
image

**Expected Result:**
Logo isdisplayed
image

**Comment by aleksandrakorolova** [comment]
Can't reproduce

**Review by yeegor — APPROVED** [review]

**Pull request merged**
