### PR TITLE
#3900 - Add error message for password

### PR DESCRIPTION
**Pull request by IrinaZhadzinets**
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3900

**Problem:**
* Password field stay green after error message

**In this PR:**
* Add new rule for password field

### CODE REVIEW

**Comment by IrinaZhadzinets** [comment]
PR was recreated because the pull request was not deployed.
Previous pull request: https://github.com/scandipwa/scandipwa/pull/4029
After comments on the code, adding a typecast (boolean to number)

**Comment by Elena-Evsa** [comment]
Boarders of field for enter password red color in case if user made mistake and click on 'Save', error message about Qty of different classes does not appear and validation shown under the field with password, but it can not very good because of length of error's text
https://vimeo.com/664207750/d9d175e664
Same logic absent for field for enter password on create account popup and page, 'Change My Password' page, could you, please, implement it 
Now on the page 'Edit Account Information':
image

**Comment by Elena-Evsa** [comment]
Error message appears, but boarders of field for enter password stay green 
image

**Comment by Elena-Evsa** [comment]
Issue 2: Please add the same logic to the New password on page "Change my password" (user can reach it after forgot password procedure)
image

**Comment by carinadues** [comment]
Issue will be fixed in https://github.com/scandipwa/scandipwa/pull/4145

**Pull request closed without merging**
