### PR TITLE
#2340 - remove gray background in list view

### PR DESCRIPTION
**Pull request by tatiana-scandi**
Additionally: remove gray background in list view

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Please, add grey stars or part of star for 5 stars
**Actual result:**
image
**Expected result:**
image

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova changed unfilled stars to gray background for both grid and list views, please, check

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi 
Safari: grid view: Unnessesary line is displayed after stars. Please, remove it
image

**Comment by aleksandrakorolova** [comment]
The last stars have gradient on product and category (grid and list view) pages if product rate <5
Please, remove this gradient 
image
image
image

**Review by zans-laksa — APPROVED** [review]
Code review passed.

**Pull request merged**
