### PR TITLE
bugfix #2761 - inadequate product prices work

### PR DESCRIPTION
**Pull request by winniepukki**
Fixes scandipwa/scandipwa#2761

### CODE REVIEW

**Comment by winniepukki** [comment]
@aleksandrakorolova please use the following list to mark QA passed cases:

_**Simple and Bundle products with customizable options:**_
- [ ] Wrong prices for bundle and simple product with customisation options #2736 – _*this requires disabling an option if its price is equalled to 0, as in the default Magento*_
- [ ] Old price doesn't change when adding item for product with customization options if discount is applied to this product #2677
- [ ] Catalog price rule doesn't apply to product options #2666
- [ ] Wrong product price for simple product with required customization if product has a special price #2674

_**Configurable products:**_
- [ ] Configurable product price not updating #2582
- [ ] Wrong prices for config products on PLP and PDP #2760

_**Both or yet unknown:**_
- [ ] Specific products don't have price on PLP and PDP #2734

_**Require implementation:**_
- [ ] Wrong product price for simple product with required customization if product has a special price #2674

**Comment by winniepukki** [comment]
@aleksandrakorolova disabled an option if its price is equalled to 0, as in the default Magento

**Comment by aleksandrakorolova** [comment]
#2736 :
Customizable option (https://pr-2773.d25kd40decjpue.amplifyapp.com/default/women/tops/test-category/simple-product-for-test-test.html):
1. Symbol '+' is displayed after name of text field or text area
2. Option is disabled if all values cost 0.00
3. Free options/values (price is equaled to 0) are missing
Screenshot 2021-06-15 at 08 22 15
Bundle product (https://pr-2773.d25kd40decjpue.amplifyapp.com/default/kids/8bunfixed.html):
1. '+ null' is displayed for free option 
Screenshot 2021-06-15 at 08 37 10

**Comment by aleksandrakorolova** [comment]
Before mentioned issues are fixed in 2736 .
Found new issues for bundle product - Symbol '+' is displayed after product option if it costs 0.00 and  Two '+' is displayed for other product options.
Screenshot 2021-06-15 at 13 36 39

**Comment by winniepukki** [comment]
@aleksandrakorolova unable to reproduce 2.0. Could you please re-check? Try [the following](https://scandipwapmrev.indvp.com/default/configurable-jeans.html) product

**Comment by aleksandrakorolova** [comment]
Can reproduce if input type - checkbox 
Screenshot 2021-06-15 at 15 00 53

**Comment by aleksandrakorolova** [comment]
@winniepukki I can't reproduce too

**Comment by aleksandrakorolova** [comment]
Checkboxes are fixed

**Comment by aleksandrakorolova** [comment]
1. Ooops page when opening product with customization options or bundle with fixed price: 
https://pr-2773.d25kd40decjpue.amplifyapp.com/default/kids/8bunfixed.html
https://pr-2773.d25kd40decjpue.amplifyapp.com/default/kids/jeans-for-girls.html
Screenshot 2021-06-16 at 12 15 41

2. Price is 0.00 for grouped product on PLP if one of the grouped product have discount
Screenshot 2021-06-16 at 12 14 35

**Review by zans-laksa — APPROVED** [review]
Code review passed.

**Pull request merged**
